DOMAIN = "gosms"

CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"
CONF_CHANNEL = "channel"
CONF_BALANCE_UPDATE_INTERVAL_MINUTES = "balance_update_interval_minutes"

DEFAULT_BALANCE_UPDATE_INTERVAL_MINUTES = 30
MIN_BALANCE_UPDATE_INTERVAL_MINUTES = 5
MAX_BALANCE_UPDATE_INTERVAL_MINUTES = 1440

SERVICE_SEND_SMS = "send_sms"
SERVICE_PREVIEW_SMS = "preview_sms"
ATTR_RECIPIENT = "recipient"
ATTR_RECIPIENTS = "recipients"
ATTR_MESSAGE = "message"
ATTR_CHANNEL = "channel"

DATA_CLIENT = "client"
DATA_COORDINATOR = "coordinator"
